name: wonder_wrap
description: App that chooses your gift using AI.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter

  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  smooth_page_indicator: ^1.1.0
  swipe_widget: ^0.0.2+1
  universal_html: ^2.2.4
  url_launcher: ^6.1.12
  appinio_swiper: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - /Users/admin/Desktop/Development/wonder_wrap/images/
    - /Users/admin/Desktop/Development/wonder_wrap/images/logo.png
    - /Users/admin/Desktop/Development/wonder_wrap/images/Starting.png
    - /Users/admin/Desktop/Development/wonder_wrap/images/AiisChoosing.png
    - /Users/admin/Desktop/Development/wonder_wrap/images/LogoTheAIHasChosenYourGift.png
    - /Users/admin/Desktop/Development/wonder_wrap/images/TextTheAIHasChosenYourGift.png
    - /Users/admin/Desktop/Development/wonder_wrap/images/swipeLeft.png
    - /Users/admin/Desktop/Development/wonder_wrap/images/swipeRight.png